name: Auto Assign Author ğŸ§‘â€ğŸ’»

on:
  pull_request_target:
    types: [ opened, reopened ]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-18.04
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
